package repository

import "context"

//go:generate esc-domain-gen -f=member.go
type MemberRepository interface {
	Start(ctx context.Context, req *UpdatePhoneReq) (*UpdatePhoneResp, error)
}

// Code generated by by esc-model-gen.
// Source: payload.UpdatePhoneResp
type UpdatePhoneResp struct {
	Phone       string
	AreaCode    string
	CaptchaCode string
	CreateTime  string
	UpdateTime  string
	CreateAt    string
	UpdateAt    string
}
