package usecase

import (
	"context"
	"gox/internal/domain/repository"
)

//go:generate esc-domain-gen -f member.go
type MemberUseCase interface {
	Start(ctx context.Context, req *UpdatePhoneReq) (*UpdatePhoneResp, error)
}

// Code generated by by esc-model-gen.
// Source: payload.UpdatePhoneReq
//
// REPLACE CAUTION!!
type UpdatePhoneReq struct {
	Phone       string
	AreaCode    string
	CaptchaCode string
	CreateTime  int64
	UpdateTime  int64
	CreateAt    int64
	UpdateAt    int64
	repository.UpdatePhoneEntity
}

// Code generated by by esc-model-gen.
// Source: payload.UpdatePhoneResp
type UpdatePhoneResp struct {
	Phone       string
	AreaCode    string
	CaptchaCode string
	CreateTime  string
	UpdateTime  string
	CreateAt    string
	UpdateAt    string
}
