package payload

import (
	"gox/internal/domain/entity"
	"gox/internal/domain/repository"
	"gox/internal/domain/usecase"
)

//go:generate esc-model-gen -replace -p2u -p2e -e member.go -u member.go -uu
//go:generate inspector -foo=bar -arg2 -arg3=123 -o ./internal/entity
type UpdatePhoneReq struct {
	Phone       string `json:"phone" binding:"required"`
	AreaCode    string `json:"area_code" binding:"required"`
	CaptchaCode string `json:"code" binding:"required"`
	CreateTime  int64  `json:"create_time"`
	UpdateTime  int64  `json:"update_time"`
	CreateAt    int64  `json:"create_at"`
	UpdateAt    int64  `json:"update_at"`

	repository.UpdatePhoneEntity
}

// Code generated by by esc-model-gen.
// Source: payload.UpdatePhoneReq
//
// REPLACE CAUTION!!
func (elem *UpdatePhoneReq) ToEntity() *entity.UpdatePhoneReq {
	return &entity.UpdatePhoneReq{
		Phone:             elem.Phone,
		AreaCode:          elem.AreaCode,
		CaptchaCode:       elem.CaptchaCode,
		CreateTime:        elem.CreateTime,
		UpdateTime:        elem.UpdateTime,
		CreateAt:          elem.CreateAt,
		UpdateAt:          elem.UpdateAt,
		UpdatePhoneEntity: elem.UpdatePhoneEntity,
	}
}

// Code generated by by esc-model-gen.
// Source: payload.UpdatePhoneReq
//
// REPLACE CAUTION!!
func (elem *UpdatePhoneReq) ToUseCase() *usecase.UpdatePhoneReq {
	return &usecase.UpdatePhoneReq{
		Phone:             elem.Phone,
		AreaCode:          elem.AreaCode,
		CaptchaCode:       elem.CaptchaCode,
		CreateTime:        elem.CreateTime,
		UpdateTime:        elem.UpdateTime,
		CreateAt:          elem.CreateAt,
		UpdateAt:          elem.UpdateAt,
		UpdatePhoneEntity: elem.UpdatePhoneEntity,
	}
}

//go:generate esc-model-gen -u=member.go -r=member.go
type UpdatePhoneResp struct {
	Phone       string `json:"phone" binding:"required"`
	AreaCode    string `json:"area_code" binding:"required"`
	CaptchaCode string `json:"code" binding:"required"`
	CreateTime  string `json:"create_time"`
	UpdateTime  string `json:"update_time"`
	CreateAt    string `json:"create_at"`
	UpdateAt    string `json:"update_at"`
}
